version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "4036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : latihan1
      MYSQL_USER : latihan1
      MYSQL_PASSWORD : latihan1
      MYSQL_ROOT_PASSWORD : latihan1
      SERVICE_TAGS : dev
      SERVICE_NAME : mysql
    networks:
      - laravel

  
  php:
    image: php:8.2.1RC1-alpine3.16
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel


# jika import library dari luar docker hub
  # php:
  #   image: php:8-fpm
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: php
  #   volumes:
  #     - ./src:/var/www/html
  #   ports:
  #     - "9000:9000"    
  #   networks:
  #     - laravel
